module.exports = {
  extends: [
    'tslint:latest',
    'tslint-microsoft-contrib',
  ],
  rulesDirectory: [
    'tslint-eslint-rules',
    'tslint-microsoft-contrib',
    'tslint-consistent-codestyle',
  ],
  rules: {
    'export-name': false,
    'import-name': false,
    'member-access': false,
    'no-as-type-assertion': true,
    'no-collapsible-if': true,
    'no-console': true,
    'no-default-export': false,
    'no-increment-decrement': false,
    'no-return-undefined': true,
    'no-static-this': true,
    'no-submodule-imports': false,
    'no-unnecessary-else': true,
    'no-unused': true,
    'parameter-properties': [ 'readonly' ],
    'trailing-comma': true,
    'triple-equals': true,
    'underscore-consistent-invocation': [ true, { style: 'static' } ],
  },
};
